[package]
name = "slipway_svg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.38.0"
serde_json = "1.0.104"
serde = { version = "1.0.180", features = ["derive"] }
resvg = "0.44.0"
usvg = "0.44.0"
